<?php

require_once(__DIR__ . "/../bootstrap/index.php");
require_once(__DIR__ . "/../sender/ImageService.php");
require_once(__DIR__ . "/../sender/LinkService.php");
require_once(__DIR__ . "/../sender/PrepareMailContent.php");
require_once(__DIR__ . "/../../library/swiftmailer/lib/swift_required.php");
require_once(__DIR__ . "/../sender/TrackingUrlObject.php");
require_once(__DIR__ . "/../sender/AttachmentObject.php");
require_once(__DIR__ . "/../sender/InterpreterTarget.php");
require_once(__DIR__ . "/../../library/swiftmailer/lib/swift_required.php");
require_once(__DIR__ . "/../sender/CustomfieldManager.php");
require_once(__DIR__ . "/../../general/misc/AutomaticCampaignObj.php");

$mailSender = new BlockedEmail();

$mailSender->start();

/**
 * Description of BlockedEmail
 *
 * @author roosevelt.diaz
 */
class BlockedEmail {

  public function start() {

    $date = "2017-03-07 08:23";
    $date = strtotime($date);
    $emails = "guerreroa1123@hotmail.com
hadder@yahoo.com
igescarria@hotamil.com
keiner-y@haotmail.com
linama232@hoymail.com
nata201@hotmail.com
arquitldos@yahoo.com
johana.vidal@hotmail.com
nathy440@hotmail.com
carmen_bautista@copservir.com
edeatom@yahoo.com
invstaelena@yahoo.com
luly896@hotmail.com
alejandrocobo_escobar@hotail.com
carlos-arturo@live.com
edinsonarangom@hotmail.com
fabiolataledocardona@yahoo.es
patty752000@hotmail.com
almacenpinturasla8a@gnail.com
anderzapata@hotmail.com
josemauriciocarrascal@ghmail.com
silvio.granados@armada.mil.co
calidelicias@msm.com
jaimejcr@yahoo.com
yeimer2011@hotmail.es
carlos.pulgarin@grupossi.com
gastonemd@hotmial.es
juank19671@outlok.com
mcqg18@homail.com
nercy1973@hotmail.com
danielmoreno@hotmail.com
giovannylopez18@hotmail.com
jjbrtgosbalcero@yahoo.com
luisa.jimenez_@yahoo.es
luz-stellita@hotmail.com
paula479@hotmail.com
paulaandrea.72@hotmail.com
amanda1@hotmail.com
anamaria1@hotmail.com
cristinita0977@hotmail.com
felipe.valderrama@hotmail.com
julioc790@hotmail.com
karitobb10@hotmail.com
mariaedithber@hotmail.com
patricia10014@hotmail.es
jalloo@hotmail.com
orlandomosquera1@gmail.co
rizo13@outlook.com
yennypaz@hotmail.com
chalo491@hotmail.com
mayerly-023@hotmail.com
anaebravo@yahoo.es
camiloeduardograjales@gnail.com
claudiaesterramirezduque@hotmail.com
eucaris2361@gmeil.com
facturacion.cali@fondex.com.co
freddyfhs@gnail.com
isauratovar55@hotmail.com
jairoarboledapuneda@yahoo.es
jhonsi18@hotmail.com
jose-901@hotmail.com.ar
malumogi@hotmail.com.co
martha198313@hotmail.com
mayorgajosacristhian@outlook.es
meli-cate@hotmial.com
nany1021@hotmail.com
nurduquebernal@gamail.com
oscarmni@yahoo.es
pati1209@hotmail.com
proveedordepanaderia@hormail.com
rafamaglioni7069@hotmsil.com
sonniabalanta@outlook.es
tavoeldogor@hotmail.com
trust10@hotmaol.co.uk
visavel1974@hotmail.com
vivito0128@gmaiil.com
ccorrea@fcbl.org
emibri@hotmail.com
gloriazapata@hotmail.com
jenniferespinozanarvaez@hotamail.com
jonathanbalanta@hotmail.com
petiza.52@yahoo.es
sampal75@yahoo.es
soffyluna506@hotmalil.com
busbano75@hotmail.es
heiandavi@yahoo.com
herrerajaramillo@hotmail.com
jhonfryhernando@hotmail.com
jorgegarces@hotmail.com
luci123@hotmail.com
luis.ortega1@hotmail.com
mabelmene1990@hotmail.com
mascastaneda@emcali.com
nenavilla7831@hotmail.com
noluis@hotmail.com
vivierzo@yahoo.com.mx
yesenia_s_s@hotmial.com
yovis2otmail.284@hotmail.com
dayanabarrera@hotmail.com
jhonjairo945@hoymail.com
nymarch@msn.com
anamilesilva@homaill.com
andres42855@hotmail.com
andresjr90@hotmail.com
bedoya_0611@hotmail.com
calvo2@hotmail.es
cassalex@outlook.com
cbastidasp@hotmail.com
clavigite1@hotamil.com
danielfelipe117@outlook.com
eliana.puerta6@hormail.com
isismosji@hotmial.com
johannarocha07@hotmail.com
leo-gonzalez18@hotmail.com
luzamparo-15@hotmail.com
marbarajad@hotmail.es
nelcy059193@hotmail.com
odir56@hotmail.com
ojisarca2011@hotmail.com
pao-tiza-59@hotmail.com
renericocastelblanco74@hotmail.com
sandritatirado@hotmail.com
a.gerenvia@lmar.com.co
aidadetallitos@hotmsil.com
alejandrabetancur@yahoo.com
andrescaisedo2010@hotmail.com
andresr1589@hotmail.com
angel.chavez@armada.mil.co
aristidez_1966@hotmail.com
dannaparra2015@hotnail.com
flor-maria78@hotmail.com
jeisonparamo0792@hotamil.com
jotamonti3000@homail.com
juancho1017@hotmail.com
kateringa77@hotmail.com
lilianazapata_2@hotmail.com
mariac@yahoo.com
mauriciom095@guimail.com
mbernat@att.net
nacasilv@homail.com
nata_castro@homael.com
nejuso.24@hotmail.es
paolamus88@hotmail.com
sandrita2804@outlook.co
vimaro83@hotmsil.com
yuripaz88@hotmai.es
amparito.25@hotmail.com
claudiavalencia@hotmail.com
johana14_22@hptmail.com
joseluiszamudio09180@autlook.com
lorenalozano81@hotmail.com
luisbedoya11@gnail.com
millerhoyos@yahoo.com
norvelydiazaguilar@yahoo.com
stevendi12@hotmail.com
valentinasanchez26@hotmail.com
avilgilro@yahoo.es
clementeim469@hotmail.com
dirley.490@gmasil.com
ganderson@hotmail.com
jorge-rios@hotmail.com
lamemi2009@hotmail.com
luis8236@hotmail.com
luisa_m_arias@hotmail.es
mariayinethcaicedo@hotamail.com
mario217@hotmail.com
mayuya303@hotail.com
millinoppua@yahoo.es
sandry83@hotmail.com
johan258@hotmail.com
triple000_@hotmail.com
vanesa214@hotmail.com
jhelman@yahoo.com
panaderiacolombia@hotmail.com
soffymazuera@yahoo.com
marthacasarez100@yahoo.com
andres-renteria@hotmail.com
enriqueo.1001@otook.com
katherine.duque@hotamil.com
ruby200@hotmail.com
zago421@yahoo.com
86javier@hotmail.es
audi_teran@yahoo.com
encanta_vida@yahoo.com
jipdocue@yahoo.es
jose.herney@hotmail.es
polobeta_4279@yahoo.com
stivel.cardozo@armada.mil.co
sus_wat@hotmail.com
carlos_vuelta.com@hotamail.com
ingenieroconstrucciones@yahoo.es
maryicastro796@gamail.com
nelec@att.net
wlrami30@yahoo.es
alexmolcomolco@yahoo.com
galvarezrivera2@yahoo.com
maeldewarriior@yahoo.com
marycecy93@hotmail.com
lucia0713@hotmail.com
arenas_fania@yahoo.es
fabidazago@hotmail.com
lacho65@hotmail.com
carlos.rojas@crscompany.co
estrellita_demar@hotmail.com
edwuardwalteros@yahoo.es
janeth_pinto@copservir.com
jfmendoza@masterteam.com
lei.bys@hotamail.com
robayo@yahoo.com
jorgero@hotmail.com
netsparker@example.com
mariaeugeoapotes@hotmsil.com
alosonhernanjimenez@yahoo.com
amasabu@hotmail.com
jessicarendon@hotmail.com
mburbanovallejo@hayoo.es
servidrog1@hormail.com
13061965@hotmail.com
abara2@hotmail.com
admon@distrimarcas-sas.com
adriana503@hotmail.com
adrianacolom@hotmail.com
adrianarboleda@hotmail.com
aguila1507@hotmail.com
aguirre_amparo@yahoo.mx
ahdias@hotmail.com
alba.1926@hotmail.com
ale__92@hotmail.com
alejandra20@yahoo.es
alejo-19781@hotmail.com
alesbucanero@yahoo.ee
alex.sepul@hotmail.com
alexafeli@hotmail.com
alexgonzalez47@hotmail.com
alexherry@hotmail.es
alexmina257@hotmail.com
aley.1996@live.com
aleysaca@otmail.com
alfonsonico321@hotmail.com
alfonsosaravia@daecsa.com
alfonsotorres@hotmail.com
alfranco15@yahoo.com
alvarezelena2014@outlook.es
alvaro-2012@hotmail.com
amartinezm7@hotmail.com
amse206@yahoo.es
ana.karina.villa@hotamil.com
ana.tores86@yahoo.com.co
anabeatnt985@yahoo.com
anadm2e@yahoo.es
114@hotmail.com
3124@hotmail.com
andres_847@hotmail.com
andresarce@outlok.com
andrespaniagua@hotmail.com
andresreca76@hormail.com
andy_@hotmail.com
angelacicedomoreno@hotymail.com
angelalopez-20@hotmail.com
angellandasuri@hotmail.com
angperez@ingeniomayaguez.com
anguizia@hotmail.es
anto12345@hotmail.com
anyelita282011@hotmail.com
aralsanco@live.com
arias_gloriaa2@hotamil.com
armaver@yahoo.es
arnol2008@yahoo.es
arsacar1961@homail.com
auto_lucita1212@iclaud.com
baanoswid@yahoo.es
bcmc16@hotmail.com
bearear_1273@yahoo.com
bekasama@hotmail.com
bigio86@hotamil.com
bryan3616@hotmail.com
bryan-523@hotmail.com
calibernal@hotamil.com
camiloruizsoto@hotmail.com
caquintero02@hotnail.com
caramjuancarlos@yahoo.com
carc_@hotmail.com
cardi91@hotmaill.com
cardocz@hotmail.es
carlosflores69@hotmail.com
carlosfrancovallejo@hotamil.com
carodadid0@yahoo.es
carpatino@hotmail.com
carvaron71@hotamil.com
castroman@hotmail.com
cefren0244@hotamil.com
celmari@msn.com
cesariano91@jhotmail.com
charlieeduard@hotmail.com
charrupi@hotmail.com
chavezleon@hotmail.com
_20@hotmail.com
chelamore@hotmail.com
clarafernan1@yahoo.es
claudia-663@hotmail.com
colombia48@hotamil.com
comchajomchar@hotmail.es
comercialcali@yahoo.com
contadoramamillo@hotnmail.com
cortez03@live.com
crisitan021@live.com.ar
cristian_vallejo.p@live.com
csandobalmera@yahoo.es
cssm12@hotmail.com
cubillosm@hotmail.com.co
d_l10@hotmail.com
dallis_18@hotmail.com
dama14@yahoo.es
dana14_@hotmail.com
danny_senad@hotmail.com
daviddu@2011hotmail.com
davidgarcia.17@outlok.com
ez2@yahoo.com
dgetial@team.com
dialcomtel@yahoo.com
diana.crespo@hotmail.com
diana_2456@hotmail.com
diana-824@hotmaail.com
dianacv@familia.co
diana-lore24@hotmail.com
dianamo109@hotmail.com
dianaxer@yahoo.com
diegofiguv1@hotmail.es
diegorodrigosuarez@yahoo.com
dieguito_sys@hotmial.com
dipina202510@yahoo.es
adora1965@hotmail.com
dita_4@yahoo.com
doravidal@hotmail.com
dpml@hotmil.es
dr.quiroz@autlook.com
edgarliz@reingenieria.com
edinson1977-25@otmail.com
edissonfajardo3149@hotmail.es
eduardo_mogollon@copservir.com
eduardocadavid@yahoo.es
eduardowalteros@yahoo.es
edw2009@hotmail.com
edwinalvear@yahoo.com
ejlunezo@yahoo.com
eldelsur527@hotamil.com
eli_torres@hm.com.co
elikka2012@yahoo.es
elisa_0771@hotmail.com
elkinieto@yahoo.com
elmorocho92@hotmail.com
elsabarrero@yahoo.com
ema6vo@yahoo.com
emejavi@yahoo.com
eni8803@hotmail.com
ramirez2010@hotmail.com
escorpion57@hotmail.com
esperanzas2578@hotmial.com
esteban249osorio@hotmaill.com
ester.shaddai@hotmail.es
esthitmauriciorivaspalma@hotmail.com
eswingarciavasquez@hotail.com
eversanch@hotamil.com
fabi565@hotmail.com
fabioburu@hotmail.com
facil.2013@live.com
fcorreatrejos@emcali.net.com
felosa28@hotmail.com
fernando.s.rodriguez@correounivalle.edu.com
fernandogalindez@hayoo.com
fernandorios90@bellsouth.net
ferneto10@yahoo.es
fleiner@hotmail.com
flsmoli@yahoo.com
frankilngordillom@yahoo.com
freddyhernandov@hotmail.com
fremuibarq@yahoo.es
freyder232826@hotmial.com
gach2019@yahoo.com
gacruz@emcali.com
gchabur@gnail.com
germonlla@yahoo.com
gevisar@yahoo.com
n-s@hotmail.com
giosamyoli@hotmail.com
girlmmeelanie@hotmail.com
gladis2911@hotmail.com
glamurtesluz@hotamil.com
graciachelita@hotamil.com
gsalazarcruz@hotamail.es
guillermogaviria@emcali.net.com
guimen@homail.com
35@hotmail.com
gv3852@outllook.com
haroldalfredo@hotmail.es
hauder@hotmail.es
hectorvargas@hotmail.com
hederbarahona@yahoo.com
hellen_rios@hotmail.com
hellento2793@hotamil.com
henao20111@hotmail.com
henry.23@hotmail.com
hernandosan@hotmail.com
hgsan16@yahoo.com
hoovermorocho@hotmail.com
hpantoja.80@yahoo.com
lopez@eldoradoaircargo.com
hucunarti@hotmail.com
hugoyara01@hotmail.com
hulalaja@yahoo.com
humbertoroman@hotmail.com
hurtadomauro@yahoo.com
india-gotika@hotmail.com
inesmunoz012@yahoo.com
ingfabioramires@yahoo.com
insoledadcv@yahoo.es
irle29@icluod.com
isabelita_2001@hotmail.com
israelsiniestra@yahoo.es
itameta@hotail.com
ivanportela@outlook.com
jagi7@yahoo.com
jaimegiron@teleplast.com.co
jaironarvaez21@yahoo.com
jaiversa@hotmail.es
jamir29@hotmail.com
jandrea22@hotamail.com
janecaaguilar66@hotmail.es
janet36@hotmail.com
jantonio1969@hotmail.com
jarconta@hotmaiol.com
jari20@hotmail.com
javidyfan@hotmail.com
javier.ocampo@outlook.com
javierhm@hotmail.com
javierpro15@outlook.co
jaz-om0208@hotamil.com
jeanpal75@yahoo.es
jeffertrujillo@hotmail.com
jenifer.br24@yahoo.com
jenny215888@hotmail.com
jessica-russi@outlok.com
jesus.lasso@yahoo.com
jeyson0426@hotmail.es
467@hotmail.com
jhonat17@hotmaiil.com
jhonatanangulo1990@outook.com
jhonperdomo@hotmail.com
jhonsito08@hotmail.com
jioba02@yahoo.es
joaquinhernandez@hotmail.com
jocarro17@yahoo.com
johanalalinda_92@hotmail.es
johanna2249@hotamil.com
john447@hotmail.com
jorge916@hotmail.com
jorgemanzano@outlook.com.co
jorge-vargas@hotmail.com
josebuitragi@rocketmail.com
jppedraza@hotmail.com
jrivera1@hotmail.com
juan12-@hotmail.com
juancalorslatorre@hotmaoil.com
juancofa@hotmail.com
juanjosediazp@gnail.com
juankasilva07@hotmail.com
juanpe66@hotmail.com
julferro1@hotamil.com
julieta1263@live.com
julio.carrasquillo@yahoo.es
kamilo19@hotmail.com
karen-llopezz@hotmail.com
katalina21@yahoo.com
kathe-herrera@hotmail.com
katiale11@yahoo.es
katiela_13@yahoo.es
kmsalazar@hotmail.com
kther02048@msn.com
ladiosa2@hotmail.com
laflaca@live.com
lanana22@hotmail.com
laou_ra95@live.com
larry_herrera@hotmial.com
lauesteca@hotmail.com
lavarini@live.com
lecastri@homail.com
lehurtado2002@yahoo.es
leididy10@yahoo.com
leidy_andrea1@live.com
leidy2008@hotmail.com
lerafi@outllok.com
leydyyaya@hotmail.com
lidatarazona@yahoo.com
linacifuentes@yahoo.es
lisbethmon@hotmail.com
lisfer1987@yahoo.com
figueroac@hotmail.com
lpatino10292000@yahoo.com
lufehicor@yahoo.co
luisalbertopelaescelis@yahoo.es
luisfe1a@hotmail.com
luisgg46@hotmial.com
lulu53@hotmail.com
lumafa2001@yahoo.com
luna-isabel@hotmail.com
luz.edna@hotmail.es
luz728@hotmail.com
lzabogal@yahoo.es
m_guzmanmorrelli@yahoo.com
mafegri@yahoo.com
mamdichi69@htmail.com
maraga@hotmail.com
marce_8786@yahoo.com
marcela_19@hotmail.com
marcelahenao65@hotmail.com
marcelahoyos@hotmail.com
marcelino_19102@gmailc.om
marcogi@hotmail.com
mare234@hotmail.com
mariafenix-36@hotmail.com
mariageovanarivas@outlook.es
marifer-3379@hotmail.com
marse121|@hotmail.com
marva66@hotmail.com
mary0217@hotmail.com
marygarcia@dazae.com
mauro.1386@hotmqil.com
mauropikoto8@hotmail.com
mayito_2007@hotmail.com
meekrocastallejo@yahoo.com
michaelprietoantolines@yahoo.com
michele.odorba@seoul.com
miguel221-@yahoo.es
mirellamillan@hotmail.com
mlozano@hotmail.com
monica_2705@hotmail.com
monikda@yahoo.com
mono_1976@hotmail.com
nabadigita@yahoo.com
nanarodri@yahoo.ie
nanducho25@hotmaiul.com
nanres80@yahoo.com
naslyrosa65@hotamil.com
naturport@emcali.net.com
naty890@hotmail.com
nayibtire@yahoo.com
nelcy71@hotmail.com
nelidau@hotmail.com
nelson-petra-@hotmail.com
neltricy@live.com
nestoraaugusto_isaza@yahoo.es
nestoral@yahoo.com
netfaly_murillo_11@hotmail.com
nodulce@yahoo.com
noralu77@hotmail.com
norbeydiazaguilar@yahoo.com
ocasmo@yahoo.es
ofmc987@yahoo.com
olgacristinam@gmail.com
olgaluciaayala@hotmail.com
olgamanjarres@yahoo.com
oliver01@hotmail.com
olyrholdin@yahoo.com
ompalacios2@misena.edu.com
oscar10_@hotmail.es
oscareduardo2812@hotmail.com
oscarlar@hotmail.com
oscarmuriel@hormail.com
oswalopez@yahoo.com
p-aleja@hotmail.com
palermo0715@hotmaill.com
palmirano1970@hotamail.com
palominoalexander7@hotmail.com
patriciaorozco59@hotamil.com
paulari@hotmail.com
paulitah13@hotmail.com
pedroa_rodriguez@homtail.com
phanarice@yahoo.com
pilararevalo@confandi.com.co
pilarborrero@live.com
pipelon23@yahoo.es
popaluma75@hotmail.es
ptoyecto-tres-3@yahoo.es
quintero17@hotmail.com
rao2121@outlook.es
rasjon@hotamil.com
raulsal27@hotmail.com
rdario3134@otmail.com
regina2015@hotmail.com
revilla1079@yahoo.com
rio.35@hotmail.com
rociovalencia@hotmail.com
rovisat2@yahoo.com
ruth049@hotmail.com
salinas-2001@hotmail.com
sami_1017@hotmail.com
lone8@hotmail.com
pddelg417451@yahoo.com
sandra.pinzon@sam.velez.com
sandracifuenteshernandez@hotmail.com
m40@hotmail.com
sara428@hotmail.com
saramezaiina@yahoo.com
sebastian091@hotmail.com
sergiobuitrago@hotmail.com
sergioyovaho@hotamil.com
seveyorrum88@hotamil.com
3962011@hotmail.com
sluga@yahoo.com
solcito-987@yahoo.com
soniczapata@hotmail.com
soraya178@hotmail.com
steven8915@hotmail.com
susana2104@hotmail.com
talelvi@hotmail.com
tanatos2702@hotmaill.com
tatianaperez8a@gmailc.om
tatis234@hotmail.com
telma@hotmail.com
tommymt323@hoymail.com
totatota@hotmail.com
tvalencia@fcbl.org
unandres8@yahoo.com
vanessa-fernandezgomez@yahoo.com
vargasselena@hotmail.com
ventaetrella1@yahoo.com.ar
vickyjp3@hotamil.com
victor_romero35@hotmail.com
victoredudardo75@yahoo.es
victorhugo1413@hotmail.com.co
vidarteo@yahoo.com
vilmarios98@hotamil.com
vimayerli-91@hotmail.com
vivian_andrea@yahoo.com
vivian-1920@h0tmail.com
wadypao@hotmail.com
willher1305@yahoo.com
willifel@yahoo.com
wj78@yahoo.com
ximiras@yahoo.com
yanetharellano@yahoo.com
yaqueline.1971@hotmail.com
yaz2882@hotmail.com
yei_2015@hotmail.com
yeisya@siamsa.com
yeo1927@hotmail.com
yoleny.zeigler@yahoo.com
yoli.campo@yahoo.cm
yolimapossu@yahoo.es
yurumara@hotmail.com
yuvonny-82@hotmail.es
zaquinru@yahoo.com
adri.rengifo@hotmail.com
adrianamillan78@hotmail.es
alicia_bastidas@hotmail.com
almacenrefripartes@homtail.com
almarociopardo@hotmail.es
alpaga_@yahoo.com
am_granados@hotmaiil.com
americadediaz@hotmail.com
anac983@hotmail.com
anmaridi19@hotmail.com
anr1060@att.net
bamboo@hotmail.com
barrera-productions@yahoo.com
besosyabrazos23@hotmail.com
cabordy@yahoo.com
cclaudiare05@hotmail.com
ccorrea15@hotmail.com
cofla331@hotmail.com
confeccionessandrey@yahoo.com
cortessalazar@yahoo.es
dialohenao@hotmail.com
duarteluna88@hotmail.com
edwingi@hotmail.com
fanysandovalospina@hotmail.com
gabriel_r910@hotmail.com
garyriverapetro@hotmail.com
gerardo_henao@yahoo.es
haidivy85@hotmail.com
hezzeraelcy@yahoo.com
ja1517@hotmail.com
jaider_juliana@hotmail.com
jaidy33@hotmail.com
jhenao14@hotmail.com
jhonatan1668@hotmail.com
jhonjagalvis-80@hotmail.com
jhonsote_26@hotmail.com
josealbertodelcampo@gmail.com
joseuriel@yahoo.es
jrq_82@hotmail.es
karend1994@hotmail.com
karolinapadi@ouhook.com
las_h_76@hotmail.com
licethgrana@gmail.co
luisanti.23@hotmail.com
luisa-rodriguez@finsa.com.co
luxeneidamomo@hotmail.com
marianaruiz84@live.com
mdpa#28@hotmail.com
os@cialsa.com
miguel_20@hotmail.com
muribe54@yahoo.com
nohemycar@hotmail.com
normasilvestre@hotmail.com
olpagil27@hotmail.com
ortega4555@hotmail.com
oscarmateo14@hotmail.com
pamela1801@hotmail.com
pino1305@hotmail.com
sanyur60@yahoo.com
sebas_rst@hotmail.es
sindy67115@hotmail.com
valengp1792@hotmail.com
verorestrepo1984@hotmail.com
vidi02@hotmail.com
yenifferlopez2006@hotmail.com
yfami812@yahoo.com";

    $emails = explode("\n", $emails);
    $inEmail = [];
    $writeConcern = new MongoDB\Driver\WriteConcern(MongoDB\Driver\WriteConcern::MAJORITY, 1000);
echo 123;
exit;
    $manager = \Phalcon\DI::getDefault()->get('mongomanager');
    $bulk = new \MongoDB\Driver\BulkWrite;
    foreach ($emails as $key) {
      $inEmail[] = $key;
    }
    $where = array("email" => ['$in' => $inEmail], "idMail" => (string) 574);
    $bulk->update($where, ['$set' => ["bounced" => (int) $date, "bouncedCode" => 200]], ['multi' => true]);
    $manager->executeBulkWrite('aio.mxc', $bulk, $writeConcern);
    exit;
  }

}
