<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7c4b6ffb4ac37ac3686dd667c3dba7a7
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'ElephantIO\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ElephantIO\\' => 
        array (
            0 => __DIR__ . '/..' . '/wisembly/elephant.io/src',
            1 => __DIR__ . '/..' . '/wisembly/elephant.io/test',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 
            array (
                0 => __DIR__ . '/..' . '/psr/log',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7c4b6ffb4ac37ac3686dd667c3dba7a7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7c4b6ffb4ac37ac3686dd667c3dba7a7::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit7c4b6ffb4ac37ac3686dd667c3dba7a7::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
